
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\fenmi\OneDrive\Desktop\test\build\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("700x450")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 450,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    638.0,
    80.0,
    image=image_image_1
)

canvas.create_text(
    639.0,
    427.0,
    anchor="nw",
    text="ver 1.0",
    fill="#000000",
    font=("Inter SemiBold", 15 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=273.0,
    y=395.0,
    width=142.0,
    height=41.0
)

canvas.create_text(
    319.0,
    357.0,
    anchor="nw",
    text="記住此帳密",
    fill="#000000",
    font=("Inter SemiBold", 14 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=292.0,
    y=354.0,
    width=20.0,
    height=20.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    350.5,
    316.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=234.0,
    y=300.0,
    width=233.0,
    height=31.0
)

canvas.create_text(
    234.0,
    276.0,
    anchor="nw",
    text="驗證碼(verification code)",
    fill="#000000",
    font=("Inter SemiBold", 14 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    205.5,
    196.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=42.0,
    y=172.0,
    width=327.0,
    height=46.0
)

canvas.create_text(
    42.0,
    148.0,
    anchor="nw",
    text="密碼(password):",
    fill="#000000",
    font=("Inter SemiBold", 14 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    205.5,
    111.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=42.0,
    y=87.0,
    width=327.0,
    height=46.0
)

canvas.create_text(
    41.0,
    63.0,
    anchor="nw",
    text="帳號(account):",
    fill="#000000",
    font=("Inter SemiBold", 14 * -1)
)
window.resizable(False, False)
window.mainloop()
